version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-1"
    REACT_APP_USERS_SERVICE_URL: "http://localhost:5001"

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo logging into ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo building images...
      - >
        docker build \
        -f services/users/Dockerfile.aws.prod \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-aws-users:prod \
        ./services/users
      - >
        docker build \
        -f services/client/Dockerfile.prod \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-aws-client:prod \
        --build-arg NODE_ENV=production \
        --build-arg REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL \
        ./services/client
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-aws-users:prod
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-aws-client:prod
